VAGKereso/apps/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    # Első feladat - A költő
    path('kolto/', lambda request: views.task(request=request, task_name="A költő"), name='kolto'),

    # Második feladat - Formalitás
    path('formalitas/', lambda request: views.task(request=request, task_name="Formalitás"), name='formalitas'),

    # Harmadik feladat - Reliving
    path('reliving/', lambda request: views.task(request=request, task_name="Reliving"), name='reliving'),


    # Első ág - Keresés
    path('kereses/', lambda request: views.branch(request=request, branch_name="Keresés"), name='kereses'),

    # Első feladat - Solar
    path('kereses/solar/', lambda request: views.branch_task(request=request, task_name="Solar", branch_name="Keresés"), name='solar'),

    # Második feladat - A kód
    path('kereses/kod/', lambda request: views.branch_task(request=request, task_name="A kód", branch_name="Keresés"), name='kod'),

    # Harmadik feladat - Ősmagyarok dicsősége
    path('kereses/osmagyarok-dicsosege/', lambda request: views.branch_task(request=request, task_name="Ősmagyarok dicsősége", branch_name="Keresés"), name='osmagyarok-dicsosege'),

    # Negyedik feladat - Iker
    path('kereses/iker/', lambda request: views.task(request=request, task_name="Iker"), name='iker'),


    # Második ág - Logika
    path('logika/', lambda request: views.branch(request=request, branch_name="Logika"), name='logika'),

    # Első feladat - A jászma
    path('logika/jatszma/', lambda request: views.branch_task(request=request, task_name="A játszma", branch_name="Logika"), name='jatszma'),

    # Második feladat - Iker 2
    path('logika/iker-2/', lambda request: views.branch_task(request=request, task_name="Iker 2", branch_name="Logika"), name='iker-2'),

    # Harmadik feladat - Nézőpont
    path('logika/nezopont/', lambda request: views.branch_task(request=request, task_name="Nézőpont", branch_name="Logika"), name='nezopont'),

    # Negyedik feladat - Szótenger
    path('logika/szotenger/', lambda request: views.task(request=request, task_name="Szótenger"), name='szotenger'),


    # Harmadik ág - Művészet
    path('muveszet/', lambda request: views.branch(request=request, branch_name="Művészet"), name='muveszet'),

    # Első feladat - A piac
    path('muveszet/piac/', lambda request: views.branch_task(request=request, task_name="A piac", branch_name="Művészet"), name='piac'),

    # Második feladat - A festmény
    path('muveszet/festmeny/', lambda request: views.branch_task(request=request, task_name="A festmény", branch_name="Művészet"), name='festmeny'),

    # Harmadik feladat - A darab
    path('muveszet/darab/', lambda request: views.branch_task(request=request, task_name="A darab", branch_name="Művészet"), name='darab'),

    # Negyedik feladat - A ritmus
    path('muveszet/ritmus/', lambda request: views.task(request=request, task_name="A ritmus"), name='ritmus'),


    # Negyedik ág - Irodalom
    path('irodalom/', lambda request: views.branch(request=request, branch_name="Irodalom"), name='irodalom'),

    # Első feladat - A mű
    path('irodalom/mu/', lambda request: views.branch_task(request=request, task_name="A mű",
                                                           branch_name="Irodalom"), name='mu'),

    # Második feladat - A zseni
    path('irodalom/zseni/', lambda request: views.branch_task(request=request, task_name="A zseni",
                                                              branch_name="Irodalom"), name='zseni'),

    # Harmadik feladat - Egy kutya
    path('irodalom/egy-kutya/', lambda request: views.branch_task(request=request, task_name="Egy kutya",
                                                                  branch_name="Irodalom"), name='egy-kutya'),

    # Negyedik feladat - A tragédiák diktátora
    path('irodalom/tragediak-diktatora/',
         lambda request: views.task(request=request, task_name="A tragédiák diktátora"), name='tragediak-diktatora'),


    # Utolsó előtti feladat - Az utolsó játszma
    path('utolso-jatszma/', lambda request: views.task(request=request, task_name="Az utolsó játszma"), name='utolso-jatszma'),

    # Utolsó feladat - A tekercs
    path('tekercs/', lambda request: views.last_task(request=request, task_name="A tekercs"), name='tekercs')
]

VAGKereso/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Main
    path('', views.index, name="index"),

    # Login
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),

    # Logout
    path('logout/', views.logout, name="logout"),

    # Tasks
    path('tasks/', include('VAGKereso.apps.tasks.urls')),

    # Registration
    # path('register/', views.register, name="register"),
    # path('create_user/', views.register, name="create")
]

VAGKereso/apps/tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Task(models.Model):
    # Task name
    name = models.CharField(max_length=100)

    # Task answer
    answer = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ClassProfile(AbstractUser):
    # The completed tasks
    completed_tasks = models.ManyToManyField(Task)

    def __str__(self):
        string = str(self.username)
        return string[0] + ". " + string[1]

    def add_task(self, task: Task):
        self.completed_tasks.add(task)

VAGKereso/apps/tasks/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required as need_login
from .models import Task, ClassProfile


def get_object(name: str) -> str:
    """Give the answer to the task."""

    for item in Task.objects.all():
        if item.name == name:
            return item


def normalize(string: str) -> str:
    """Normalize a string (eg.: convert á to a)"""

    original_letters = {"á": "a",
               "é": "e",
               "í": "i",
               "ó": "o",
               "ö": "o",
               "ő": "o",
               "ú": "u",
               "ü": "u",
               "ű": "u",
               " ": "_"}

    letters = {}

    for letter in original_letters:
        try:
            letters.update({letter: original_letters.get(letter),
                            letter.upper(): original_letters.get(letter).upper()})
        except:
            pass

    new_string = ""

    for character in string:
        if character in letters:
            new_string += letters.get(character)
            continue
        new_string += character

    return new_string


def get_unlocked(class_profile: ClassProfile, branch_name: str) -> list[int]:
    """Get the unlocked tasks in a branch."""

    # Get the completed tasks
    completed_tasks = [task.name for task in class_profile.completed_tasks.all()]

    # Define the branches
    branches = {"Keresés": {"Solar": 1,
                           "A kód": 2,
                           "Ősmagyarok dicsősége": 3,
                           "Iker": 4},
                "Logika": {"A játszma": 1,
                           "Iker 2": 2,
                           "Nézőpont": 3,
                           "Szótenger": 4},
                "Művészet": {"A piac": 1,
                             "A festmény": 2,
                             "A darab": 3,
                             "A ritmus": 4},
                "Irodalom": {"A mű": 1,
                             "A zseni": 2,
                             "Egy kutya": 3,
                             "A tragédiák diktátora": 4}}

    # Get the tasks in the current branch
    tasks_in_branch = branches.get(branch_name)

    # Get the completed tasks in the current branch
    completed_tasks = [tasks_in_branch.get(item) for item in completed_tasks if item in tasks_in_branch]

    if len(completed_tasks) == 0:
        return [1]
    return list(range(1, completed_tasks[-1] + 2))




@need_login
def task(request: HttpRequest, task_name: str) -> HttpResponse:
    """Show and test a task."""

    if request.method == "POST":
        answer = request.POST.get("answer")

        if answer:
            object = get_object(task_name)
            if answer.lower() == object.answer:
                request.user.add_task(object)
                return redirect("index")
    return render(request, normalize(task_name) + ".html")


@need_login
def branch_task(request: HttpRequest, task_name: str, branch_name: str) -> HttpResponse:
    if request.method == "POST":
        answer = request.POST.get("answer")

        if answer:
            object = get_object(task_name)
            if answer.lower() == object.answer:
                request.user.add_task(object)
                return redirect("tasks:" + normalize(branch_name).lower())
    return render(request, normalize(task_name) + ".html")

@need_login
def branch(request: HttpRequest, branch_name: str) -> HttpResponse:
    unlocked = get_unlocked(class_profile=request.user, branch_name=branch_name)
    return render(request, normalize(branch_name) + ".html", {"buttons": unlocked})


@need_login
def last_task(request: HttpRequest, task_name: str) -> HttpResponse:
    """Show and test the last task."""

    if request.method == "POST":
        answer = request.POST.get("answer")

        if answer:
            object = get_object(task_name)
            if answer.lower() == object.answer:
                request.user.add_task(object)
                return render(request=request, template_name="end.html")
    return render(request, normalize(task_name) + ".html")

VAGKereso/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required as need_login
from .apps.tasks.models import ClassProfile

task_ids = {"A költő": 1,
            "Formalitás": 2,
            "Reliving": 3,
            "Keresési ág": 4,
            "Logikai ág": 5,
            "Művészeti ág": 6,
            "Irodalmi ág": 7,
            "Az utolsó játszma": 8,
            "A tekercs": 9}


def get_unlocked(class_profile: str) -> list:
    """Get the unlocked tasks."""

    tasks = class_profile.completed_tasks.all()
    print(set([task.name for task in tasks]))
    if all(task_name in [task.name for task in tasks] for
           task_name in ["Iker", "Szótenger", "A ritmus", "A tragédiák diktátora"]):
        value = True
    else:
        value = False

    tasks = [task.name for task in tasks if task.name in task_ids]
    print(tasks)
    if len(tasks) == 0:
        return [1]
    if task_ids.get(tasks[-1]) < 3:
        plus = 2
    elif value:
        plus = 6
    else:
        plus = 5

    print(list(range(1, task_ids.get(tasks[-1]) + plus)))
    return list(range(1, task_ids.get(tasks[-1]) + plus))


@need_login
def index(request: HttpRequest) -> HttpResponse:
    """Main Page"""

    unlocked = get_unlocked(request.user)

    return render(request, "index.html", {"buttons": unlocked})


@need_login
def logout(request: HttpRequest) -> HttpResponse:
    """Log Out and Redirect to the Login Page"""

    auth_logout(request=request)

    return redirect(to="login")


"""def register_page(request: HttpRequest) -> HttpResponse:
    return render(request=request, template_name="create_user.html")


def register(request: HttpRequest) -> HttpResponse:
    classes = {"1A": "htuy8g",
               "1B": "tSvjxK",
               "1C": "WRmFvX",
               "2A": "srTsqA",
               "2B": "Bp081p",
               "2C": "omrCRO",
               "3A": "lvdAAj",
               "3B": "lp8MWc",
               "teachers": "fhpNUp",
               "tibor": "0jmlMD"}

    for username in classes:
        password = classes.get(username)

        ClassProfile.objects.create_user(username=username, password=password)

        print(f"{username} created.")

    return redirect("register")"""

VAGKereso/templates/A_festmeny.html
<!DOCTYPE html>
<html>
<head>
    <title>A festmény</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>A festmény</h2>
        <iframe src="https://drive.google.com/file/d/1QMASIl8soVyRfn2QSOYohzBE6xBtdEpC/preview" width="640" height="480" allow="autoplay"></iframe>

        <form action="{% url 'tasks:festmeny' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/A_jatszma.html
<!DOCTYPE html>
<html>
<head>
    <title>A játszma</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>A játszma</h2>
        <iframe src="https://drive.google.com/file/d/1WyC-QNhZaSk3bvbR8HlpTyIB7WlVYDGQ/preview" width="640" height="480" allow="autoplay"></iframe>
        <form action="{% url 'tasks:jatszma' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/A_kod.html
<!DOCTYPE html>
<html>
<head>
    <title>A kód</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>A kód</h2>
        <form action="{% url 'tasks:kod' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/A_mu.html
<!DOCTYPE html>
<html>
<head>
    <title>A mű</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>A mű</h2>
        <iframe src="https://drive.google.com/file/d/1WxZqzWCMrbHh3AYBP-x-tFK-hBkYcgtO/preview" width="640" height="480" allow="autoplay"></iframe>

        <form action="{% url 'tasks:mu' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/A_zseni.html
<!DOCTYPE html>
<html>
<head>
    <title>A zseni</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>A zseni</h2>
        <iframe src="https://drive.google.com/file/d/1U8U0p75j9a6m8XKhdUa-FvniqfaX9yLw/preview" width="640" height="480" allow="autoplay"></iframe>

        <form action="{% url 'tasks:zseni' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/Egy_kutya.html
<!DOCTYPE html>
<html>
<head>
    <title>Egy kutya</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>Egy kutya</h2>

        <form action="{% url 'tasks:egy-kutya' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/Irodalom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Irodalmi Ág</title>
</head>
<script>
    function goToParent() {
        window.location.href = "/";
    }
</script>
<style>
    body {
        background-color: #181a19;
    }
    h1 {
        font-family: bookman old style;
        font-size: 100px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    h2 {
        font-family: bookman old style;
        font-size: 50px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    .logout {
        position: absolute;
        top: 10px;
        left: 10px;
        background-color: green;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 5px;
    }
    .buttons {
        text-align: center;
        margin-top: 20px;
    }
    .button {
        display: none;
        margin: 5px;
        padding: 10px 20px;
        background-color: white;
        border: 1px solid black;
        border-radius: 5px;
    }
</style>
<body>
    <h1>Irodalmi Ág</h1>
    <h2>
        {{ user.username }}
    </h2>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div class="buttons">
        <button class="button" id="button1" onclick="window.location.href='/tasks/irodalom/mu/'">A mű</button>
        <br>
        <button class="button" id="button2" onclick="window.location.href='/tasks/irodalom/zseni/'">A zseni</button>
        <br>
        <button class="button" id="button3" onclick="window.location.href='/tasks/irodalom/egy-kutya/'">Egy kutya</button>
        <br>
        <button class="button" id="button4" onclick="window.location.href='/tasks/irodalom/tragediak-diktatora/'">A tragédiák diktátora</button>
    </div>
</body>
<script>
    var buttonsToShow = {{ buttons|safe }};

    buttonsToShow.forEach(buttonNumber => {
        document.getElementById('button' + buttonNumber).style.display = 'inline-block';
    });
</script>
</html>

VAGKereso/templates/Kereses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Keresési Ág</title>
</head>
<script>
    function goToParent() {
        window.location.href = "/";
    }
</script>
<style>
    body {
        background-color: #181a19;
    }
    h1 {
        font-family: bookman old style;
        font-size: 100px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    h2 {
        font-family: bookman old style;
        font-size: 50px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    .logout {
        position: absolute;
        top: 10px;
        left: 10px;
        background-color: green;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 5px;
    }
    .buttons {
        text-align: center;
        margin-top: 20px;
    }
    .button {
        display: none;
        margin: 5px;
        padding: 10px 20px;
        background-color: white;
        border: 1px solid black;
        border-radius: 5px;
    }
</style>
<body>
    <h1>Keresési Ág</h1>
    <h2>
        {{ user.username }}
    </h2>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div class="buttons">
        <button class="button" id="button1" onclick="window.location.href='/tasks/kereses/solar/'">Solar</button>
        <br>
        <button class="button" id="button2" onclick="window.location.href='/tasks/kereses/kod/'">A kód</button>
        <br>
        <button class="button" id="button3" onclick="window.location.href='/tasks/kereses/osmagyarok-dicsosege/'">Ősmagyarok dicsősége</button>
        <br>
        <button class="button" id="button4" onclick="window.location.href='/tasks/kereses/iker/'">Iker</button>
    </div>
</body>
<script>
    var buttonsToShow = {{ buttons|safe }};

    buttonsToShow.forEach(buttonNumber => {
        document.getElementById('button' + buttonNumber).style.display = 'inline-block';
    });
</script>
</html>

VAGKereso/templates/Logika.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logikai Ág</title>
</head>
<script>
        function goToParent() {
            window.location.href = "/";
        }
</script>
<style>
    body {
        background-color: #181a19;
    }
    h1 {
        font-family: bookman old style;
        font-size: 100px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    h2 {
        font-family: bookman old style;
        font-size: 50px;
        margin: 25px;
        text-align: center;
        color: white;
    }
    .logout {
        position: absolute;
        top: 10px;
        left: 10px;
        background-color: green;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 5px;
    }
    .buttons {
        text-align: center;
        margin-top: 20px;
    }
    .button {
        display: none;
        margin: 5px;
        padding: 10px 20px;
        background-color: white;
        border: 1px solid black;
        border-radius: 5px;
    }
</style>
<body>
    <h1>Logikai Ág</h1>
    <h2>
        {{ user.username }}
    </h2>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div class="buttons">
        <button class="button" id="button1" onclick="window.location.href='/tasks/logika/jatszma/'">A játszma</button>
        <br>
        <button class="button" id="button2" onclick="window.location.href='/tasks/logika/iker-2/'">Iker 2</button>
        <br>
        <button class="button" id="button3" onclick="window.location.href='/tasks/logika/nezopont/'">Nézőpont</button>
        <br>
        <button class="button" id="button4" onclick="window.location.href='/tasks/logika/szotenger/'">Szótenger</button>
    </div>
</body>
<script>
    var buttonsToShow = {{ buttons|safe }};

    buttonsToShow.forEach(buttonNumber => {
        document.getElementById('button' + buttonNumber).style.display = 'inline-block';
    });
</script>
</html>

VAGKereso/templates/Nezopont.html
<!DOCTYPE html>
<html>
<head>
    <title>Nézőpont</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>Nézőpont</h2>
        <a href="https://prezi.com/view/QFqkNgXuGaP2RLS1F3F5/" target="_blank">Prezentáció</a>
        <form action="{% url 'tasks:nezopont' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>

VAGKereso/templates/Szotenger.html
<!DOCTYPE html>
<html>
<head>
    <title>Szótenger</title>
    <script>
        function goToParent() {
            window.location.href = "/";
        }
    </script>
    <style>
        body {
            background-color: #181a19;
            color: white;
            text-align: center;
            font-size: 18px;
            margin-top: 10vh;
            font-family: Arial, sans-serif;
        }
        input[type="text"] {
            width: 200px;
            padding: 5px;
            margin: 10px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        #id {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        }
        .logout {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: green;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <button class="logout" onclick="goToParent()">Főoldal</button>
    <div>
        <h2>Szótenger</h2>
        <p></p>
        <p>portré</p>
        <p>dopaminreceptor</p>
        <p>hoppá</p>
        <p>húskonzerv</p>
        <p>rézfúvóshangszer</p>
        <p>kampányhajrá</p>
        <p>cukorrépa</p>
        <p>szimmetriatengely</p>
        <p>lepkebáb</p>
        <p>anyajuh</p>
        <p>denevérfaj</p>
        <p>leheletfinom</p>

        <form action="{% url 'tasks:szotenger' %}" method="post">
            {% csrf_token %}
            <input type="text" name="answer" placeholder="Írd ide válaszod"><br>
            <button type="submit">Küldés</button>
        </form>
    </div>
</body>
</html>